set(_CATKIN_CURRENT_PACKAGE "new_work")
set(new_work_VERSION "0.0.0")
set(new_work_MAINTAINER "sun234 <sun234@todo.todo>")
set(new_work_PACKAGE_FORMAT "2")
set(new_work_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(new_work_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(new_work_BUILDTOOL_DEPENDS "catkin")
set(new_work_BUILDTOOL_EXPORT_DEPENDS )
set(new_work_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(new_work_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(new_work_TEST_DEPENDS )
set(new_work_DOC_DEPENDS )
set(new_work_URL_WEBSITE "")
set(new_work_URL_BUGTRACKER "")
set(new_work_URL_REPOSITORY "")
set(new_work_DEPRECATED "")